version: '3.8'
services:

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234  # id root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: sh -c "npx prisma migrate deploy && npm run start"
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - dev_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8088:80
    depends_on:
      - db
    environment:
      PMA_HOST : db
      MYSQL_ROOT_PASSWORD: 1234  # id root
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data: