###
GET http://localhost:3000/

###
GET http://localhost:3000/api/products/

###
GET http://localhost:3000/api/products/2

###
GET http://localhost:3000/api/categorys/

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "toshiba",
  "price": 22323,
  "categoryId": 3
}

###
PATCH  http://localhost:3000/api/products/1
Content-Type: application/json

{
  "name": "Zenbook 13 pro",
  "price": 2599,
  "categoryId": 3
}

###
DELETE http://localhost:3000/api/products/2

###
DELETE http://localhost:3000/api/categorys/3